export const LOGIN = "LOGIN";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const GET_STATISTIC_TODAY = "GET_STATISTIC_TODAY";
export const UPDATE_DATA_WEEK = "UPDATE_DATA_WEEK";
export const UPDATE_STATISTIC_DATA = "UPDATE_STATISTIC_DATA";
export const GET_INFOR_PAYMENT = "GET_INFOR_PAYMENT";